hyperlinks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path(
        '',
        include(
            'landing.urls',
            namespace='landing'
        )
    ),

    path(
        'links/',
        include(
            'links.urls',
            namespace='links'
        )
    ),
]

landing/urls.py
from django.urls import path

from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.MainView.as_view(), name='main')
]

links/urls.py
from django.urls import path

from . import views

app_name = 'landing'

urlpatterns = [
    path('<int:pk>/update/', views.LinkUpdateView.as_view(), name='link_update'),
    path('<int:pk>/delete/', views.LinkDeleteView.as_view(), name='link_delete'),
]

links/models.py
from django.db import models
from django.urls import reverse_lazy


class Link(models.Model):
    title = models.CharField(max_length=256)

    url = models.URLField(unique=True)

    keywords = models.CharField(max_length=2048, null=True, blank=True)

    description = models.CharField(max_length=2048, null=True, blank=True)

    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('links:link_detail', args=[self.pk])

links/forms.py
from django import forms

from links import services
from .models import Link


class LinkForm(forms.ModelForm):
    def save(self, commit=True):
        meta = services.link_metadata(self.cleaned_data['url'])

        self.instance.title = meta['title']

        if meta['keywords'] is not None:
            self.instance.keywords = meta['keywords'].lower()

        if meta['description'] is not None:
            self.instance.description = meta['description']

        return super().save(commit)

    class Meta:
        model = Link
        fields = ('url',)


class LinkUpdateForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('title', 'keywords', 'description')

landing/views.py
from django.urls import reverse_lazy
from django.views import generic
from links.models import Link
from links.forms import LinkForm


class MainView(generic.CreateView):
    model = Link
    form_class = LinkForm

    template_name = 'landing/main.html'

    success_url = reverse_lazy('landing:main')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['link_list'] = Link.objects.all()

        return context

links/views.py
from django.urls import reverse_lazy
from django.views import generic

from links.models import Link
from links.forms import LinkUpdateForm


class LinkUpdateView(generic.UpdateView):
    model = Link
    form_class = LinkUpdateForm

    success_url = reverse_lazy('landing:main')


class LinkDeleteView(generic.DeleteView):
    model = Link

    success_url = reverse_lazy('landing:main')

hyperlinks/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <title>{% block page_title %}{% endblock %}</title>
</head>

<body>

<div class="container" style="max-width: 900px; margin-top: 16px">
  <div class="d-none d-md-block" style="margin-top: 48px"></div>
  {% block page_body %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

landing/templates/landing/main.html
{% extends 'base.html' %}

{% block page_body %}
  <div class="row">
    <div class="col-12">
      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group">
          <input type="url" name="url" class="form-control form-control-lg" placeholder="Enter link">
          <div class="input-group-append">
            <button type="submit" class="btn btn-lg btn-primary">Save</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-12">
      {% for link in link_list %}
        <div class="card mb-3">
          <div class="card-body">
            <h2 class="card-title text-truncate">{{ link.title }}</h2>
            <h5 class="small">{{ link.keywords|default_if_none:'' }}</h5>

            <p class="text-justify">
              {{ link.description|default_if_none:'' }}
            </p>

            <div class="text-truncate">
              <a href="{{ link.url }}" class="card-link">{{ link.url }}</a>
            </div>
          </div>

          <div class="card-footer text-muted">
            <div class="float-right">
              <a href="{% url 'links:link_update' link.pk %}" class="btn btn-primary btn-sm"
                 style="margin-top: -10px; margin-bottom: -5px">Update</a>
              <a href="{% url 'links:link_delete' link.pk %}" class="btn btn-danger btn-sm"
                 style="margin-top: -10px; margin-bottom: -5px">Delete</a>
            </div>

            {{ link.create_date }}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

links/templates/links/link_confirm_delete.html
{% extends 'base.html' %}

{% block page_body %}
  <form action="" method="post">
  {% csrf_token %}
    <div class="card">
      <div class="card-body">
        Are you sure you want to delete the link:

        <p>
          <a href="{{ link.url }}" class="card-link">{{ link.url }}</a>
        </p>

        <div>
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </form>
{% endblock %}

links/templates/links/link_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block page_body %}
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
{% endblock %}